---
- hosts: all
  gather_facts: false
  tasks:
    - name: initial upgrade
      become: true
      dnf:
        name: "*"
        state: latest

    - name: enable other repository
      become: true
      command:
        cmd: dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-32.noarch.rpm

    - name: enable copr repository
      become: true
      yum_repository:
        name: "copr:copr.fedorainfracloud.org:{{ item[0] }}:{{ item[1] }}"
        file: "_copr:copr.fedorainfracloud.org:{{ item[0] }}:{{ item[1] }}"
        description: "{{ item[2] }}"
        baseurl: "{{ copr_url }}/results/{{ item[0] }}/{{ item[1] }}/fedora-$releasever-$basearch/"
        gpgkey: "{{ copr_url }}/results/{{ item[0] }}/{{ item[1] }}/pubkey.gpg"
        gpgcheck: yes
        enabled: yes
        skip_if_unavailable: yes
      vars:
        copr_url: https://download.copr.fedorainfracloud.org
      loop:
        - [nforro, i3-gaps, i3-gaps]
        - [odilhao, i3lock-color, i3lock-color]

    - name: install packages
      become: true
      dnf:
        name:
          - rofi
          - xbacklight
          - i3-gaps
          - i3lock-color
          - nitrogen
          - polybar
          - neofetch
          - rxvt-unicode
          - pass
          - light
        state: latest
    
    - name: install other tools
      become: true
      dnf:
        name: "https://kojipkgs.fedoraproject.org//packages/fontawesome-fonts/4.7.0/8.fc32/noarch/fontawesome-fonts-4.7.0-8.fc32.noarch.rpm"
        state: present

    - name: download cica zip
      get_url:
        url: https://github.com/miiton/Cica/releases/download/v5.0.1/Cica_v5.0.1_with_emoji.zip
        dest: /home/ryoo/work/src/cica.zip

    - name: unzip cica
      become: true
      unarchive:
        src: /home/ryoo/work/cica/cica.zip
        creates: /usr/share/fonts/cica
        dest: /usr/share/fonts/cica

    - name: clone fzf
      git:
        repo: "https://github.com/junegunn/fzf.git"
        depth: 1
        dest: /home/ryoo/.fzf

    - name: install fzf
      command:
        cmd: sh /home/ryoo/.fzf/install --no-bash
        creates: /home/ryoo/.fzf/bin/fzf
