---
- hosts: all
  gather_facts: false
  tasks:
    - name: initial upgrade
      become: true
      dnf:
        name: "*"
        state: latest

    - name: enable other repository
      become: true
      command:
        cmd: dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-32.noarch.rpm

    - name: enable copr repository
      become: true
      command:
        cmd: dnf copr enable -y {{ item }}
      loop:
        - nforro/i3-gaps
        - odilhao/i3lock-color

    - name: install dzen2 for i3-gaps
      become: true
      dnf:
        name: https://download-ib01.fedoraproject.org/pub/fedora/linux/releases/31/Everything/x86_64/os/Packages/d/dzen2-0.8.5-24.20100104svn.fc31.x86_64.rpm

    - name: install packages
      become: true
      dnf:
        name:
          - rofi
          - xbacklight
          - i3-gaps
          - i3lock-color
          - nitrogen
          - polybar
          - neofetch
          - rxvt-unicode
          - pass
          - light
        state: latest
    
    - name: install other tools
      become: true
      dnf:
        name: "https://kojipkgs.fedoraproject.org//packages/fontawesome-fonts/4.7.0/8.fc32/noarch/fontawesome-fonts-4.7.0-8.fc32.noarch.rpm"
        state: present

    - name: create cica dir
      become: true
      file:
        path: /usr/share/fonts/cica
        state: directory
        owner: root
        group: root

    - name: unzip cica
      become: true
      unarchive:
        src: https://github.com/miiton/Cica/releases/download/v5.0.1/Cica_v5.0.1_with_emoji.zip
        dest: /usr/share/fonts/cica

    - name: clone fzf
      git:
        repo: "https://github.com/junegunn/fzf.git"
        depth: 1
        dest: /home/ryoo/.fzf

    - name: install fzf
      command:
        cmd: sh /home/ryoo/.fzf/install --no-bash
        creates: /home/ryoo/.fzf/bin/fzf
