#!/bin/bash

SETUPDIR=$(dirname $0)

# functions
usage() {
  echo "Usage: ./run [check|install]"
  exit 1
}

check() {
  ansible-playbook -i localhost, -c local $SETUPDIR/install_fedora.yaml --check --ask-become-pass
}

install() {
  ansible-playbook -i localhost, -c local $SETUPDIR/install_fedora.yaml --ask-become-pass
}

# main
if [ "$#" -ne 1 ]; then
  usage
  exit 1
fi

case $1 in
  "check" )
    check;;
  "install" )
    install;;
  *)
    usage;;
esac
